# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install app dependencies
RUN npm install --production --ignore-scripts

# Copy source code
COPY . .

# Build the project (if needed). Many MCP servers written in TS will have a build step.
RUN npm run build || echo "No build step needed"

# Expose the port if necessary
EXPOSE 8080

# Run the MCP server using the entry point file referenced in the README
CMD ["node", "screenshot-mcp-server.mjs"]
